repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    entry: just isort
    language: system
    always_run: true
    pass_filenames: false
  - id: black
    name: black
    entry: just black
    language: system
    always_run: true
    pass_filenames: false
  - id: flake8
    name: flake8
    entry: just flake8
    language: system
    always_run: true
    pass_filenames: false
  - id: mypy
    name: mypy
    entry: just mypy
    language: system
    always_run: true
    pass_filenames: false
  - id: pytest
    name: pytest
    entry: just test
    language: system
    always_run: true
    pass_filenames: false
