name: CI

on:
  push:
  pull_request:
  # run CI every day to catch issues with external dependency updates
  # (18th minute to avoid delays during high GH Action loads)
  schedule:
    - cron: '18 13 * * *'

jobs:
  test:
    name: "Test Python ${{ matrix.python-version }} (${{ (matrix.pin-versions == '' && 'Latest Dependencies') || (contains(matrix.pin-versions, 'pydantic<2') && 'Pydantic v1') || 'Compatibility Check' }})"
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
        # TODO: Import error with boto3==1.10.0 on python3.12 through boto3->botocore->urllib3
        pin-versions: ["", '"\"pydantic<2\""', '"\"boto3==1.10.0; python_version<''3.12''\"" "\"boto3==1.20.0; python_version>=''3.12''\"" pydantic==1.7.1 "\"importlib_metadata==1.0.0; python_version<''3.8''\""']

    env:
      PYTHON: ${{ matrix.python-version }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py

    - uses: extractions/setup-just@v1

    - name: install
      run: 'just install-dev ${{ matrix.pin-versions }}'
    - name: Lint
      run: just pre-commit
    - name: test
      run: just test
    - name: coverage
      run: just coverage

    - uses: codecov/codecov-action@v3
      with:
        file: coverage.xml
        env_vars: PYTHON

  deploy:
    name: Build and Deploy
    needs: test
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - uses: extractions/setup-just@v1

    - name: install
      run: just install-deploy

    - name: build
      run: just build

    - name: upload to pypi
      run: twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_token }}
